name: deploy

on:
  push:
    branches:
    - prod

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-22.04
    steps:
    - name: Deploy
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 200.234.232.44
        port: 2222
        username: gaston
        key: ${{ secrets.PRIVATE_KEY }}
        script: "sudo /var/www/html/majosfera-back/.github/workflows/script.sh"
